version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo "Building the application"
      - npm run build

post_build:
  commands:
    - echo "Uploading files to S3 bucket 'matchando'"
    - aws s3 cp dist/ s3://matchando/ --recursive --content-type "binary/octet-stream"
    - echo "Setting proper Content-Type for uploaded files"
    - |
      for file in $(aws s3 ls s3://matchando/ --recursive | awk '{print $4}'); do
        case "$file" in
          *.html)
            content_type="text/html"
            ;;
          *.js)
            content_type="application/javascript"
            ;;
          *.css)
            content_type="text/css"
            ;;
          *.png)
            content_type="image/png"
            ;;
          *.jpg|*.jpeg)
            content_type="image/jpeg"
            ;;
          *.svg)
            content_type="image/svg+xml"
            ;;
          *)
            content_type="binary/octet-stream"
            ;;
        esac
        aws s3 cp "s3://matchando/$file" "s3://matchando/$file" --content-type "$content_type" --metadata-directive REPLACE
      done
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
